[project]
name = "langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.0.27",
    "langchain-core>=1.2.13",
    "langchain-openai>=1.1.10",
]
